### ISSUE TITLE
kube-proxy panics after a LoadBalancer service is re-created

### ISSUE THREAD

**Issue by sebsoto** [microsoft/Windows-Containers#103]
Kubernetes version: 1.20
Windows version: Windows Server 2019 10.0.17763.1817
Issue occurs on OpenShift Container Platform v4.7.3

kube-proxy panics when a LoadBalancer service is re-created.  The LoadBalancer was associated with a deployment with multiple pods spread across nodes.

LoadBalancer Service:
```
apiVersion: v1
kind: Service
metadata:
  name: win-webserver
  labels:
    app: win-webserver
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: win-webserver
  type: LoadBalancer

```
Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-webserver
  name: win-webserver
  namespace: default
spec:
  securityContext:
  selector:
    matchLabels:
      app: win-webserver
  replicas: 3
  template:
    metadata:
      labels:
        app: win-webserver
      name: win-webserver
    spec:
      podSecurityContext:
      tolerations:
      - key: "os"
        value: "Windows"
        Effect: "NoSchedule"
      containers:
      - name: windowswebserver
        securityContext:
          windowsOptions:
            runAsUserName: "ContainerAdministrator"
        image: mcr.microsoft.com/powershell:lts-nanoserver-1809
        imagePullPolicy: IfNotPresent
        command:
        - pwsh.exe
        - -command
        - $listener = New-Object System.Net.HttpListener; $listener.Prefixes.Add('http://*:80/'); $listener.Start();Write-Host('Listening at http://*:80/'); while ($listener.IsListening) { $context = $listener.GetContext(); $response = $context.Response; $content='<html><body><H1>Windows Container Web Server</H1></body></html>'; $buffer = [System.Text.Encoding]::UTF8.GetBytes($content); $response.ContentLength64 = $buffer.Length; $response.OutputStream.Write($buffer, 0, $buffer.Length); $response.Close(); };
      nodeSelector:
        beta.kubernetes.io/os: windows

```

The kube-proxy exe was run as:
```
kube-proxy.exe --v=4 --proxy-mode=kernelspace --feature-gates=WinOverlay=true --hostname-override=ip-10-0-129-184.ec2.internal --kubeconfig=c:\k\kubeconfig --cluster-cidr=10.132.1.0/24 --log-dir=C:\var\log\kube-proxy\ --logtostderr=false --network-name=OVNKubernetesHybridOverlayNetwork --source-vip=10.132.1.170 --enable-dsr=false
```
Here is the portion of the logs where the panic occurs:
```
time="2021-03-18T19:55:37Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12"
time="2021-03-18T19:55:37Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 13"
time="2021-03-18T19:55:37Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10"
E0318 19:55:42.028808    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:45.209619    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:48.125508    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:51.930551    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:52.025381    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:52.121118    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
time="2021-03-18T19:55:55Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12" 
time="2021-03-18T19:55:55Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10" 
time="2021-03-18T19:55:55Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12"
time="2021-03-18T19:55:55Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 13"
time="2021-03-18T19:55:55Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10"
E0318 19:55:55.311274    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:55.416569    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:55.499572    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:55.640196    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:55.731000    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:55.816898    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12" 
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10" 
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12"
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 13"
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10"
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12" 
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10" 
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12"
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 13"
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10"
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12"
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10" 
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12"
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 13"
time="2021-03-18T19:55:57Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10"
E0318 19:55:57.397147    3808 proxier.go:1137] Endpoint information not available for service default/win-webserver. Not applying any policy 
E0318 19:55:57.547539    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:57.636353    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:57.730110    3808 proxier.go:1188] Policy creation failKubernetes version: 1.20
Windows version: Windows Server 2019 10.0.17763.1817
ed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:57.883467    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:57.972311    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
E0318 19:55:58.472063    3808 proxier.go:1188] Policy creation failed: hcnCreateLoadBalancer failed in Win32: The reference is invalid in the JSON document. (0x803b001c) {"Success":false,"Error":"The reference is invalid in the JSON document. A Reference is required","ErrorCode":2151350300} 
time="2021-03-18T19:56:00Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12" 
time="2021-03-18T19:56:00Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10" 
time="2021-03-18T19:56:00Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12"
time="2021-03-18T19:56:00Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 13"
time="2021-03-18T19:56:00Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10"
time="2021-03-18T19:56:00Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12"
time="2021-03-18T19:56:00Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10"
time="2021-03-18T19:56:00Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 12"
time="2021-03-18T19:56:00Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 13"
time="2021-03-18T19:56:00Z" level=info msg="currentVersion.Major < versionRange.MinVersion.Major: 9, 10"
panic: runtime error: invalid memory address or nil pointer dereference 
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x205c0dc]

goroutine 100 [running]:
k8s.io/kubernetes/pkg/proxy/winkernel.(*Proxier).syncProxyRules(0xc0000cd500)
        /remote-source/build/windows-machine-config-operator/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/winkernel/proxier.go:1124 +0x9dc
k8s.io/kubernetes/pkg/util/async.(*BoundedFrequencyRunner).tryRun(0xc00028c5a0)
        /remote-source/build/windows-machine-config-operator/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/async/bounded_frequency_runner.go:292 +0xbe
k8s.io/kubernetes/pkg/util/async.(*BoundedFrequencyRunner).Loop(0xc00028c5a0, 0xc0000820c0)
        /remote-source/build/windows-machine-config-operator/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/async/bounded_frequency_runner.go:203 +0x21b
k8s.io/kubernetes/pkg/proxy/winkernel.(*Proxier).SyncLoop(0xc0000cd500)
        /remote-source/build/windows-machine-config-operator/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/winkernel/proxier.go:752 +0x72
created by k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run
        /remote-source/build/windows-machine-config-operator/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:778 +0x855

```
Link to code for reference: https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/proxy/winkernel/proxier.go#L1124

Steps to reproduce:
1) Create LoadBalancer
2) Create deployment
3) Delete LoadBalancer
4) Re-create LoadBalancer

At this point kube-proxy will have crashed.

**Comment by sebsoto** [comment]
Full kube-proxy logs:
[kube-proxy.exe.ERROR.txt](https://github.com/microsoft/Windows-Containers/files/6167002/kube-proxy.exe.ERROR.txt)
[kube-proxy.exe.INFO.txt](https://github.com/microsoft/Windows-Containers/files/6167003/kube-proxy.exe.INFO.txt)
[kube-proxy.exe.WARNING.txt](https://github.com/microsoft/Windows-Containers/files/6167004/kube-proxy.exe.WARNING.txt)

**Comment by jsturtevant** [comment]
This looks like an issue with kubeproxy and not the the platform itself?  Could you open an issue in https://github.com/kubernetes/kubernetes?

**Comment by sebsoto** [comment]
Sure thing. Created it here https://github.com/kubernetes/kubernetes/issues/100384

**Comment by vrapolinario** [comment]
Thanks both - sorry for the delay on triaging this. I'll close the issue for now as this is being investigated elsewhere.
