### ISSUE TITLE
System.Speech SpeechSynthesizer - Unable to run tests 

### ISSUE THREAD

**Issue by Orphic16** [microsoft/Windows-Containers#139]
Using image mcr.microsoft.com/dotnet/framework/sdk:4.8

Trying to run tests in that involve SpeechSynthesizer it fails on the line:
`_speechSynthesizer.Volume = 100;`

Stack Trace:
`Initialization method AlertsTests.AlertsViewModelTest.MyTestInitialize threw exception. System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {D9F6EE60-58C9-458B-88E1-2F908FD7F87C} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))..
Stack Trace:
    at System.Speech.Internal.ObjectTokens.RegistryDataKey..ctor(String fullPath, IntPtr regHandle)
 at System.Speech.Internal.ObjectTokens.RegistryDataKey.Open(String registryPath, Boolean fCreateIfNotExist)
 at System.Speech.Internal.ObjectTokens.SAPICategories.DefaultDeviceOut()
 at System.Speech.Internal.Synthesis.VoiceSynthesis..ctor(WeakReference speechSynthesizer)
 at System.Speech.Synthesis.SpeechSynthesizer.get_VoiceSynthesizer()
 at System.Speech.Synthesis.SpeechSynthesizer.set_Volume(Int32 value)`

Any way to get these tests to execute using the 4.8 sdk image?

**Comment by vrapolinario** [comment]
While you're using a .Net image, I'd assume the required component is not part of the base image, so assigning this to both Weijuan and Richard to investigate this scenario. As always, one alternative is to try out the new Server image: https://techcommunity.microsoft.com/t5/containers/announcing-a-new-windows-server-container-image-preview/ba-p/2304897

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@richlander, @weijuans-msft, please provide an update or close this issue.

**Comment by judyliu-ms** [comment]
Hi @Orphic16, was the [new Server image ](https://techcommunity.microsoft.com/t5/containers/announcing-a-new-windows-server-container-image-preview/ba-p/2304897) was able to solve your issue?

**Comment by judyliu-ms** [comment]
Since there has been no activity, going to close out this issue and assume that the Server image was able to solve this issue.
