### ISSUE TITLE
How can I run WSUS on winndows container.

### ISSUE THREAD

**Issue by Rickylss** [microsoft/Windows-Containers#251]
I'm tring to run WSUS on container server:ltsc2022.  After installation, startting service failed with command: `.\wsusutil.exe postinstall CONTENT_DIR=C:\WSUS`. 

This is the output of the log:

```powershell
2022-07-20 14:41:37  Postinstall started
2022-07-20 14:41:37  Detected role services: Api, UI, WidDatabase, Services
2022-07-20 14:41:37  Start: LoadSettingsFromParameters
2022-07-20 14:41:37  Content local is: True
2022-07-20 14:41:37  Content directory is: C:\WSUS
2022-07-20 14:41:37  SQL instname is:
2022-07-20 14:41:37  End: LoadSettingsFromParameters
2022-07-20 14:41:37  Start: Run
2022-07-20 14:41:37  Fetching WsusAdministratorsSid from registry store
2022-07-20 14:41:37  Value is (null)
2022-07-20 14:41:37  Configuring content directory...
2022-07-20 14:41:37  Configuring groups...
2022-07-20 14:41:37  Starting group configuration for WSUS Administrators...
2022-07-20 14:41:37  Group does not already exist in the registry
2022-07-20 14:41:37  System.Runtime.InteropServices.COMException (0x80070842): The Server service is not started.

   at System.DirectoryServices.DirectoryEntry.RefreshCache()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoMachineInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.ContextForType(Type t)
   at System.DirectoryServices.AccountManagement.Principal.set_Name(String value)
   at Microsoft.UpdateServices.Administration.ConfigureGroups.FetchOrCreateGroup(PrincipalContext context, String name, String description)
   at Microsoft.UpdateServices.Administration.ConfigureGroups.SetupGroup(PrincipalContext context, String groupName, String description, String registryValue)
   at Microsoft.UpdateServices.Administration.ConfigureGroups.Run(Action`1 logWriter)
   at Microsoft.UpdateServices.Administration.PostInstall.Run()
   at Microsoft.UpdateServices.Administration.PostInstall.Execute(String[] arguments)
```

It looks like the `LanmanServer` is not started.  Start `LanmanServer` manually failed too.

```powershell
PS C:\> Get-Service -Name Server

Status   Name               DisplayName
------   ----               -----------
Stopped  LanmanServer       Server

PS C:\> net start server
The Server service is starting.
The Server service could not be started.

A system error has occurred.

System error 2 has occurred.

The system cannot find the file specified.
```

By the way, I start container with `process` isolation modes instead of `hyperv` which cause `srvnet  & srv2` services start failed.

So, is there any way to start  `LanmanServer` in a windows container? How can I run WSUS on winndows container?

**Comment by weijuans-msft** [comment]
Windows containers do not support Windows Update or WSUS. Here is our official docs on updating Windows containers.

Why did you need to set up WSUS? Are you running on a managed K8s service? If so what it is? Or you run on something else?

**Comment by Rickylss** [comment]
Thanks for your reply.
Actually, I am not running on a k8s service. I want to manage the update of VMs and PCs by WSUS. And the reason we use container rather than VM is that we thought container is less overhead and easy to use.
Yes, it is a very chaotic environment. So, we turn to VM now.
