### ISSUE TITLE
Newtonsoft.Json.JsonReaderException

### ISSUE THREAD

**Issue by ntrappe-msft** [microsoft/Windows-Containers#411]
**Describe the bug**
When starting up Docker Desktop, we see giant `JsonReaderException` error.

```ruby
Newtonsoft.Json.JsonReaderException:
Unexpected character encountered while parsing value: n. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__10.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__17.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<SwitchDaemonAsync>d__29.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 260
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Engines.Engines.<SwitchDaemonAsync>d__29.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 276
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Engines.Engines.<SwitchDaemonAsync>d__29.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 280
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Services.DesktopService.<SwitchDaemonAsync>d__3.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.ApiServices\Services\DesktopService.cs:line 36
```

**To Reproduce** 
- Start up Docker Desktop. If you don't have it installed, download it [here](https://www.docker.com/products/docker-desktop/).
- A Docker window should pop up with the error message.
- If you quit and restart Docker Desktop, the same window and error message will appear.

**Expected behavior**
Expect Docker Desktop to start up successfully.

**Configuration:**
- Edition: Server 2022 Standard
- Base Image: Windows Server Core LTSC 2022
- Container Engine: Docker
- Container Engine Version: 24.0.2 (`cb74dfc`)

**Comment by ntrappe-msft** [comment]
**Background:**
This error occurs when there is a mismatch between the host OS and the platform OS. The most typically way this error appears is when the Docker platform is set to Linux containers (by default) and you start up Docker Desktop. However, you may _also_ see this error if the platform is set to Linux containers and you try to use a docker command (e.g. `docker images`) or a docker command that invokes Windows (e.g. `docker pull mcr.microsoft.com/windows/servercore:ltsc2022`).

**Solution:**
This isn't the most intuitive error but it means that the platform is set to Linux containers while the host is clearly Windows. To fix this, change the platform to use Windows containers. With Docker running, right-click the little docker icon (black whale) in the system tray. Click **`"Switch to Windows containers"`**. To confirm that you have switched (there can be a 30s delay), right-click again on the icon and if you see the option **`"Switch to Linux containers"`** you know that it's now using Windows containers. Try any of the commands again and they should succeed.
